#Based on https://github.com/AbdBarho/stable-diffusion-webui-docker

version: '3.9'

x-base_service: &base_service
    ports:
      - "7860:7860"
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output
    stop_signal: SIGINT
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 16G
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [all,capabilities=utility]

name: webui-docker

services:
  download:
    build: ./services/download/
    volumes:
      - *v1

  auto: &automatic
    <<: *base_service
    build: ./services/AUTOMATIC1111
    image: sd-auto:58
    environment:
      - CLI_ARGS=--allow-code --xformers --enable-insecure-extension-access --api --theme dark --enable-console-prompts --gradio-img2img-tool color-sketch --update-check --no-half-vae --opt-sdp-attention	
#      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api

